const quizData = {
    "Huquqshunoslik": [
        { q: "O'zbekiston Respublikasining Konstitutsiyasi qachon qabul qilingan?", o: ["1992-yil 8-dekabr", "1991-yil 1-sentyabr", "1993-yil 10-dekabr", "1990-yil 20-iyun"], c: 0 },
        { q: "Davlat hokimiyatining birdan-bir manbai kim?", o: ["Prezident", "Oliy Majlis", "Xalq", "Sud"], c: 2 },
        { q: "O'zbekiston bayrog'ida nechta yulduz bor?", o: ["10 ta", "14 ta", "12 ta", "15 ta"], c: 2 },
        { q: "Konstitutsiya necha bo'limdan iborat?", o: ["4 ta", "6 ta", "5 ta", "8 ta"], c: 1 },
        { q: "O'zbekiston madhiyasi matni muallifi kim?", o: ["A. Oripov", "E. Vohidov", "Mirtemir", "Zulfiya"], c: 0 },
        { q: "Saylov huquqi necha yoshdan boshlanadi?", o: ["16 yosh", "21 yosh", "18 yosh", "20 yosh"], c: 2 },
        { q: "Prezident necha yil muddatga saylanadi?", o: ["5 yil", "7 yil", "4 yil", "10 yil"], c: 1 },
        { q: "Konstitutsiyaning qaysi moddasida inson huquqlari keltirilgan?", o: ["1-modda", "13-modda", "18-modda", "Hammasi"], c: 3 },
        { q: "O'zbekiston poytaxti qaysi shahar?", o: ["Samarqand", "Buxoro", "Toshkent", "Xiva"], c: 2 },
        { q: "Davlat tili haqidagi qonun qachon qabul qilingan?", o: ["1989-yil", "1991-yil", "1992-yil", "1990-yil"], c: 0 },
        { q: "Oliy Majlis necha palatadan iborat?", o: ["1 ta", "2 ta", "3 ta", "4 ta"], c: 1 },
        { q: "Qoraqalpog'iston Respublikasining maqomi qanday?", o: ["Viloyat", "Suveren respublika", "Tuman", "Shahar"], c: 1 },
        { q: "Ma'muriy javobgarlik necha yoshdan boshlanadi?", o: ["14 yosh", "16 yosh", "18 yosh", "12 yosh"], c: 1 },
        { q: "O'zbekiston gerbi muallifi kim?", o: ["A. Oripov", "A. Mahmudov", "M. Nabiyev", "O'. Tansiqboyev"], c: 2 },
        { q: "Oila kodeksi qachon qabul qilingan?", o: ["1998-yil", "1992-yil", "2000-yil", "1995-yil"], c: 0 },
        { q: "Sud hokimiyati qonun chiqaruvchiga bo'ysunadimi?", o: ["Ha", "Yo'q (mustaqil)", "Faqat qisman", "Prezident buyrug'i bilan"], c: 1 },
        { q: "Mehnat kodeksiga ko'ra ish vaqti haftasiga necha soat?", o: ["36 soat", "40 soat", "48 soat", "42 soat"], c: 1 },
        { q: "Ayollarga beriladigan dekret ta'tili necha kun?", o: ["100 kun", "126 kun", "150 kun", "90 kun"], c: 1 },
        { q: "Konstitutsiyaning 1-moddasi qanday boshlanadi?", o: ["O'zbekiston - respublika", "O'zbekiston - suveren davlat", "O'zbekiston - boy davlat", "O'zbekiston - xalq davlati"], c: 1 },
        { q: "Referendum nima?", o: ["Siyosiy partiya", "Umumxalq ovoz berishi", "Sud majlisi", "Konstitutsiya turi"], c: 1 },
        { q: "Vazirlar Mahkamasi nima bilan shug'ullanadi?", o: ["Qonun chiqarish", "Ijro etish", "Sud qilish", "Tekshirish"], c: 1 },
        { q: "Fuqarolik necha yoshdan olinadi?", o: ["Tug'ilgandan", "16 yoshdan", "18 yoshdan", "14 yoshdan"], c: 0 },
        { q: "Mahalla nima?", o: ["Hukumat organi", "O'zini o'zi boshqarish organi", "Siyosiy partiya", "Tuman bo'limi"], c: 1 },
        { q: "Huquqiy davlat nima?", o: ["Qonun ustuvor davlat", "Boy davlat", "Kichik davlat", "Kuchli armiyali davlat"], c: 0 },
        { q: "Omonat daxlsizligi nima?", o: ["Bankdagi pul daxlsizligi", "Uy daxlsizligi", "Xat daxlsizligi", "Hammasi"], c: 3 },
        { q: "Bolalar huquqlari konvensiyasi qachon qabul qilingan?", o: ["1989-yil", "1992-yil", "1945-yil", "2000-yil"], c: 0 },
        { q: "Ekologik huquq nimani himoya qiladi?", o: ["Odamlarni", "Atrof-muhitni", "Hayvonlarni", "Binolarni"], c: 1 },
        { q: "Intellektual mulk nima?", o: ["Uy", "Mashina", "Mualliflik huquqi", "Yer"], c: 2 },
        { q: "Vasiylik nima?", o: ["Yetim bolalarga qarash", "Qarindoshlik", "Ish berish", "Sudlashish"], c: 0 },
        { q: "Fuqarolik pasporti necha yoshda beriladi?", o: ["14 yosh", "16 yosh", "18 yosh", "20 yosh"], c: 1 }
    ],
    "Tarix": [
        { q: "Amir Temur qachon tug'ilgan?", o: ["1336-yil", "1342-yil", "1405-yil", "1300-yil"], c: 0 },
        { q: "Amir Temurning onasi kim?", o: ["Tegina begim", "Saroymulkxonim", "Bibixonim", "Gavharshodbegim"], c: 0 },
        { q: "Zahiriddin Muhammad Bobur qachon vafot etgan?", o: ["1530-yil", "1500-yil", "1545-yil", "1525-yil"], c: 0 },
        { q: "Boburning mashhur asari?", o: ["Turkiy devon", "Boburnoma", "Hamsa", "O'tkan kunlar"], c: 1 },
        { q: "Alisher Navoiy qachon tug'ilgan?", o: ["1441-yil", "1401-yil", "1501-yil", "1341-yil"], c: 0 },
        { q: "Mirzo Ulug'bek kimning nabirasi?", o: ["Amir Temur", "Shohruh Mirzo", "Boyqaro", "Bobur"], c: 0 },
        { q: "Qachon O'zbekiston SSSR tarkibidan chiqdi?", o: ["1991-yil", "1990-yil", "1992-yil", "1989-yil"], c: 0 },
        { q: "Jaloliddin Manguberdi mo'g'ullarga qarshi qaysi daryo bo'yida jang qilgan?", o: ["Sirdaryo", "Amudaryo", "Hind daryosi", "Nil"], c: 2 },
        { q: "Beruniyning vatani qayer?", o: ["Xorazm", "Buxoro", "Samarqand", "Andijon"], c: 0 },
        { q: "Ibn Sino jahon ilm-fanida qanday nom bilan tanilgan?", o: ["Avitsenna", "Al-Fraganus", "Al-Xorazmiy", "Farobiy"], c: 0 },
        { q: "O'rta Osiyoda birinchi akademiya qanday nomlangan?", o: ["Ma'mun akademiyasi", "Ulug'bek maktabi", "Nizomiya", "Dorulhikma"], c: 0 },
        { q: "Qaysi shahar 'Sharq darvozasi' deb atalgan?", o: ["Xiva", "Toshkent", "Qo'qon", "Buxoro"], c: 1 },
        { q: "Buxoro amirligi qachon tugatilgan?", o: ["1920-yil", "1917-yil", "1924-yil", "1900-yil"], c: 0 },
        { q: "Qadimgi Xorazm davlati poytaxti?", o: ["Kat", "Urganch", "Xiva", "Nukus"], c: 0 },
        { q: "Amir Temur necha yil hukmronlik qildi?", o: ["35 yil", "25 yil", "45 yil", "50 yil"], c: 0 },
        { q: "Islom Karimov O'zbekistonning nechanchi prezidenti?", o: ["Birinchi", "Ikkinchi", "Uchinchi", "To'rtinchi"], c: 0 },
        { q: "Buyuk ipak yo'li tushunchasini kim kiritgan?", o: ["Ferdinand Rixtgofen", "Marko Polo", "Beruniy", "Navoiy"], c: 0 },
        { q: "Turkiston general-gubernatorligi qachon tuzilgan?", o: ["1867-yil", "1860-yil", "1875-yil", "1880-yil"], c: 0 },
        { q: "Jadidchilik harakatining asoschisi kim?", o: ["Mahmudxo'ja Behbudiy", "Fitrat", "Cho'lpon", "Abdulla Qodiriy"], c: 0 },
        { q: "Afg'onistonda 'Boburiylar' sulolasiga kim asos solgan?", o: ["Bobur", "Humoyun", "Akbar", "Shohjahon"], c: 0 },
        { q: "Amir Temur va Boyazid o'rtasidagi jang qachon bo'lgan?", o: ["1402-yil", "1400-yil", "1405-yil", "1395-yil"], c: 0 },
        { q: "O'zbek tiliga davlat tili maqomi qachon berilgan?", o: ["1989-yil 21-oktyabr", "1991-yil 1-sentyabr", "1992-yil 8-dekabr", "1990-yil 20-iyun"], c: 0 },
        { q: "Mirzo Ulug'bekning asosiy asari?", o: ["Ziji jadidi Ko'ragoniy", "Hamsa", "Tib qonunlari", "Matematika"], c: 0 },
        { q: "Qadimgi yunon tarixchisi Gerodot kim haqida yozgan?", o: ["Massagetlar (To'maris)", "Boburiylar", "Temuriylar", "Somoniylar"], c: 0 },
        { q: "Arablarning O'rta Osiyoga yurishi qaysi asrda boshlangan?", o: ["VII asr", "VIII asr", "IX asr", "VI asr"], c: 0 },
        { q: "Shohizinda ansambli qaysi shaharda?", o: ["Samarqand", "Buxoro", "Xiva", "Termiz"], c: 0 },
        { q: "Qo'qon xonligi qachon Rossiya tomonidan bosib olingan?", o: ["1876-yil", "1865-yil", "1870-yil", "1880-yil"], c: 0 },
        { q: "Imom Buxoriyning eng mashhur asari?", o: ["Sahihi Buxoriy", "Tib qonunlari", "Zij", "Hamsa"], c: 0 },
        { q: "Samarqand qachon O'zbekiston poytaxti bo'lgan?", o: ["1925-1930 yillar", "1930-1940 yillar", "1920-1925 yillar", "1991-yildan beri"], c: 0 },
        { q: "Ikkinchi jahon urushida O'zbekistondan necha kishi qatnashgan?", o: ["1.5 million", "2 million", "1 million", "500 ming"], c: 0 }
    ],
    "Geografiya": [
        { q: "O'zbekistonning eng uzun daryosi qaysi?", o: ["Amudaryo", "Sirdaryo", "Zarafshon", "Norin"], c: 0 },
        { q: "O'zbekistonning eng baland cho'qqisi?", o: ["Hazrati Sulton", "G'alaba", "Adelung", "Beshtor"], c: 0 },
        { q: "Dunyodagi eng katta qit'a qaysi?", o: ["Osiyo", "Amerika", "Afrika", "Antarktida"], c: 0 },
        { q: "Qaysi okean eng kattasi?", o: ["Tinch okeani", "Atlantika", "Hind okeani", "Shimoliy muz okeani"], c: 0 },
        { q: "Quyoshga eng yaqin sayyora?", o: ["Merkuriy", "Venera", "Yer", "Mars"], c: 0 },
        { q: "O'zbekiston necha davlat bilan chegaradosh?", o: ["5 ta", "4 ta", "6 ta", "3 ta"], c: 0 },
        { q: "Farg'ona vodiysi qaysi tog'lar orasida?", o: ["Tyan-shan va Pomir-Oloy", "Ural", "Kavkaz", "Himolay"], c: 0 },
        { q: "Yerning tabiiy yo'ldoshi nima?", o: ["Oy", "Mars", "Quyosh", "Yupiter"], c: 0 },
        { q: "Afrika qit'asidagi eng katta cho'l?", o: ["Sahroi Kabir", "Gobi", "Qizilqum", "Kalahari"], c: 0 },
        { q: "Eng sovuq qit'a?", o: ["Antarktida", "Arktika", "Shimoliy Amerika", "Yevropa"], c: 0 },
        { q: "O'zbekistonning maydoni qancha?", o: ["448.9 ming km kv", "400 ming km kv", "500 ming km kv", "440 ming km kv"], c: 0 },
        { q: "Dunyodagi eng baland cho'qqi?", o: ["Everest", "K2", "G'alaba", "Monblan"], c: 0 },
        { q: "Qaysi daryo Misrda oqadi?", o: ["Nil", "Amazonka", "Ganga", "Amur"], c: 0 },
        { q: "Qora dengizga qaysi davlat chiqadi?", o: ["Turkiya", "O'zbekiston", "Eron", "Xitoy"], c: 0 },
        { q: "Yer sayyorasi nechanchi o'rinda turadi?", o: ["Uchinchi", "Birinchi", "Beshinchi", "To'rtinchi"], c: 0 },
        { q: "Eng katta orol qaysi?", o: ["Grenlandiya", "Madagaskar", "Islandiya", "Yava"], c: 0 },
        { q: "Avstraliya poytaxti qaysi shahar?", o: ["Kanberra", "Sidney", "Melburn", "Vellington"], c: 0 },
        { q: "Qaysi mamlakat poytaxti Tokio?", o: ["Yaponiya", "Xitoy", "Koreya", "Vyetnam"], c: 0 },
        { q: "Eng chuqur ko'l qaysi?", o: ["Baykal", "Orol", "Kaspiy", "Viktoriya"], c: 0 },
        { q: "Ekvaor chizig'i yerni nimaga bo'ladi?", o: ["Shimoliy va Janubiy yarim sharga", "Sharqiy va G'arbiy", "Hech narsaga", "Qutblarga"], c: 0 },
        { q: "Fransiya poytaxti?", o: ["Parij", "London", "Rim", "Berlin"], c: 0 },
        { q: "O'zbekistonning eng past nuqtasi?", o: ["Minkebulak botig'i", "Orol", "Ustyurt", "Zarafshon"], c: 0 },
        { q: "Amazonka daryosi qaysi qit'ada?", o: ["Janubiy Amerika", "Shimoliy Amerika", "Afrika", "Osiyo"], c: 0 },
        { q: "Sahroi Kabir qayerda joylashgan?", o: ["Shimoliy Afrikada", "Janubiy Afrikada", "Osiyoda", "Avstraliyada"], c: 0 },
        { q: "Eng kichik qit'a qaysi?", o: ["Avstraliya", "Yevropa", "Janubiy Amerika", "Antarktida"], c: 0 },
        { q: "Orol dengizi hozir qanday holatda?", o: ["Qurib borayotgan", "To'layotgan", "O'zgarmagan", "Chuchuklashgan"], c: 0 },
        { q: "Vatikan qayerda joylashgan?", o: ["Rim shahri ichida", "Parijda", "Ispaniyada", "Gretsiyada"], c: 0 },
        { q: "Toshkent shahri qaysi daryo bo'yida?", o: ["Chirchiq", "Amudaryo", "Sirdaryo", "Surxondaryo"], c: 0 },
        { q: "Eng ko'p aholili davlat (2025 yilda)?", o: ["Hindiston", "Xitoy", "AQSH", "Indoneziya"], c: 0 },
        { q: "Dunyo okeani nechta?", o: ["5 ta", "4 ta", "3 ta", "6 ta"], c: 0 }
    ],
    "Adabiyot": [
        { q: "Alisher Navoiyning 'Xamsa'si nechta dostonni o'z ichiga oladi?", o: ["5 ta", "4 ta", "6 ta", "3 ta"], c: 0 },
        { q: "'O'tkan kunlar' asari muallifi kim?", o: ["Abdulla Qodiriy", "Cho'lpon", "Fitrat", "G'afur G'ulom"], c: 0 },
        { q: "O'zbek adabiyoti otasi kim?", o: ["Alisher Navoiy", "Lutfiy", "Sakkokiy", "Bobur"], c: 0 },
        { q: "G'afur G'ulomning mashhur asari?", o: ["Shum bola", "Sariq devni minib", "Mehrobdan chayon", "Ufq"], c: 0 },
        { q: "Cho'lponning haqiqiy ismi nima?", o: ["Abdulhamid Sulaymon o'g'li", "Abdulla Qodiriy", "Usmon Nosir", "Zulfiya"], c: 0 },
        { q: "Zulfiyaxonim qaysi shoirning rafiqasi bo'lgan?", o: ["Hamid Olimjon", "Oybek", "Mirtemir", "G'afur G'ulom"], c: 0 },
        { q: "'Mehrobdan chayon' asari qahramoni kim?", o: ["Anvar", "Otabek", "Yodgor", "Kumush"], c: 0 },
        { q: "Alisher Navoiyning ustozi kim?", o: ["Abdurahmon Jomiy", "Lutfiy", "Sakkokiy", "Gadoiy"], c: 0 },
        { q: "O'zbekiston madhiyasi matnini kim yozgan?", o: ["Abdulla Oripov", "Erkin Vohidov", "Zulfiya", "Oybek"], c: 0 },
        { q: "Zahiriddin Muhammad Boburning she'rlar devoni qanday ataladi?", o: ["Turkiy devon", "Boburnoma", "G'aroyib us-sig'ar", "Navodir un-nihoya"], c: 0 },
        { q: "Erkin Vohidovning mashhur she'ri?", o: ["O'zbegim", "Vatandosh", "Ayol", "Bahor"], c: 0 },
        { q: "Abdulla Qahhorning hajviy asari?", o: ["Anor", "Sinchalak", "O'tmishdan ertaklar", "Sarob"], c: 0 },
        { q: "Oybekning mashhur romani?", o: ["Navoiy", "Qutlug' qon", "Oltin vodiy", "Quyosh qoraymas"], c: 1 },
        { q: "Tog'ay Murodning asari?", o: ["Ot kishnagan oqshom", "Yulduzlar mangu yonadi", "Ufq", "Lolaqizg'aldoq"], c: 0 },
        { q: "'Sariq devni minib' asari muallifi?", o: ["Xudoyberdi To'xtaboyev", "Abdulla Qodiriy", "Said Ahmad", "O'tkir Hoshimov"], c: 0 },
        { q: "Said Ahmadning hajviy asari?", o: ["Kelinlar qo'zg'oloni", "Ufq", "Jimjitlik", "Sinchalak"], c: 0 },
        { q: "O'tkir Hoshimovning eng mashhur romani?", o: ["Ikki eshik orasi", "Dunyoning ishlari", "Tushda kechgan umrlar", "Bahor qaytmaydi"], c: 0 },
        { q: "Navoiyning 'Hayrat ul-abror' dostoni nima haqida?", o: ["Falsafiy va axloqiy masalalar", "Sevgi", "Sayohat", "Urush"], c: 0 },
        { q: "'Layli va Majnun' muallifi?", o: ["Alisher Navoiy", "Nizomiy Ganjaviy", "Fuzuliy", "Hammasi"], c: 3 },
        { q: "Hamid Olimjonning ballatasi?", o: ["Oygul bilan Baxtiyor", "O'zbegim", "Bahor keldi", "Vatan"], c: 0 },
        { q: "Abdulla Oripov qaysi she'riy to'plami bilan tanilgan?", o: ["Munojot", "Yillar armoni", "Ruhim", "Hikmatlar"], c: 0 },
        { q: "G'afur G'ulomning 'Men yahudiy emasman' she'ri nima haqida?", o: ["Gumanizm va urush", "Sevgi", "Tabiat", "Boylik"], c: 0 },
        { q: "Fitratning asari?", o: ["Abulfayzxon", "O'tkan kunlar", "Kecha va kunduz", "Navoiy"], c: 0 },
        { q: "Zulfiya nima uchun 'Baxt shoirasi' deyiladi?", o: ["Vafodorlik va sadoqat kuychisi", "Boyligi uchun", "Sayohat qilgani uchun", "Urushda qatnashgani uchun"], c: 0 },
        { q: "Sadriddin Ayniyning asari?", o: ["Esdaliklar", "Navoiy", "Ufq", "Anor"], c: 0 },
        { q: "Mirkarim Osim asosan nima haqida yozgan?", o: ["Tarixiy shaxslar", "Kosmos", "Kelajak", "Sevgi"], c: 0 },
        { q: "Asqad Muxtorning asari?", o: ["Chinor", "Opa-singillar", "Tug'ilish", "Daryo"], c: 0 },
        { q: "Mirtemirning tug'ilgan joyi?", o: ["Turkiston (Qozog'iston)", "Toshkent", "Andijon", "Buxoro"], c: 0 },
        { q: "Cho'lponning 'Kecha va kunduz' romani bosh qahramoni?", o: ["Zebiniso (Zebi)", "Kumush", "Zaynab", "Ra'no"], c: 0 },
        { q: "Doston nima?", o: ["Katta hajmli she'riy asar", "Qisqa hikoya", "Drama", "Roman"], c: 0 }
    ],
    "Fizika": [
        { q: "Nyutonning ikkinchi qonuni formulasini ko'rsating.", o: ["F=ma", "E=mc2", "P=UI", "v=s/t"], c: 0 },
        { q: "Elektr qarshilik birligi nima?", o: ["Om", "Amper", "Volt", "Vatt"], c: 0 },
        { q: "Kuchlanish birligi nima?", o: ["Volt", "Om", "Amper", "Gerts"], c: 0 },
        { q: "Zichlik qanday formula bilan topiladi?", o: ["p=m/V", "F=mg", "s=vt", "a=v/t"], c: 0 },
        { q: "Suv necha gradusda qaynaydi?", o: ["100 C", "0 C", "50 C", "200 C"], c: 0 },
        { q: "Ohm qonuni formulasi?", o: ["I=U/R", "P=UI", "Q=mcT", "F=ma"], c: 0 },
        { q: "Yorug'lik tezligi qancha?", o: ["300 000 km/s", "100 000 km/s", "340 m/s", "1 000 km/s"], c: 0 },
        { q: "Kuch o'lchov birligi?", o: ["Nyuton", "Joul", "Vatt", "Paskal"], c: 0 },
        { q: "Bosim birligi nima?", o: ["Paskal", "Bar", "Torr", "Nyuton"], c: 0 },
        { q: "Issiqlik miqdori birligi?", o: ["Joul", "Kaloriya", "Gradus", "Vatt"], c: 0 },
        { q: "Energiya saqlanish qonunini kim ochgan?", o: ["Lomonosov va Lavuazye", "Eynshteyn", "Nyuton", "Faradey"], c: 0 },
        { q: "Gravitatsiya doimiysini kim aniqlagan?", o: ["Kavendish", "Nyuton", "Galiley", "Arximed"], c: 0 },
        { q: "Elektr toki nima?", o: ["Zaryadlangan zarralarning tartibli harakati", "Issiqlik harakati", "Havo oqimi", "Suv oqimi"], c: 0 },
        { q: "Magnit maydonini nima hosil qiladi?", o: ["Harakatlanayotgan zaryadlar", "Tinch turgan zaryadlar", "Issiqlik", "Tovush"], c: 0 },
        { q: "Arximed qonuni nima haqida?", o: ["Suyuqlikka botirilgan jismga ta'sir etuvchi kuch", "Yorug'lik", "Elektr", "Magnetizm"], c: 0 },
        { q: "Vatt nimaning o'lchov birligi?", o: ["Quvvat", "Ish", "Kuch", "Energiya"], c: 0 },
        { q: "Transformator nima uchun xizmat qiladi?", o: ["Kuchlanishni o'zgartirish", "Tokni to'xtatish", "Issiqlik berish", "Nur chiqarish"], c: 0 },
        { q: "Absolyut nol harorat qancha?", o: ["-273.15 C", "0 C", "-100 C", "100 C"], c: 0 },
        { q: "Qattiq jismning suyuqlikka aylanishi?", o: ["Erish", "Qaynash", "Bug'lanish", "Sublimatsiya"], c: 0 },
        { q: "Gazning suyuqlikka aylanishi?", o: ["Kondensatsiya", "Erish", "Bug'lanish", "Kristallanish"], c: 0 },
        { q: "Yorug'likning sinishi nima?", o: ["Ikki muhit chegarasidan o'tayotganda yo'nalishini o'zgartirishi", "Qaytishi", "Yutilishi", "Tarqalishi"], c: 0 },
        { q: "Ovoz tezligi havoda qancha?", o: ["340 m/s", "300 000 km/s", "1000 m/s", "100 m/s"], c: 0 },
        { q: "Elektronning zaryadi qanday?", o: ["Manfiy", "Musbat", "Neytral", "O'zgaruvchan"], c: 0 },
        { q: "Protonning zaryadi qanday?", o: ["Musbat", "Manfiy", "Neytral", "Yo'q"], c: 0 },
        { q: "Atom nimalardan iborat?", o: ["Yadro va elektronlar", "Faqat protonlar", "Molekulalar", "Hujayralar"], c: 0 },
        { q: "Qaysi metall eng yaxshi o'tkazgich?", o: ["Kumush", "Mis", "Oltin", "Alyuminiy"], c: 0 },
        { q: "Inersiya nima?", o: ["Jismning o'z holatini saqlash xususiyati", "Harakat", "To'xtash", "Tezlanish"], c: 0 },
        { q: "Radioaktivlikni kim kashf qilgan?", o: ["Bekkerel", "Kyuri", "Rezerford", "Eynshteyn"], c: 0 },
        { q: "Molekula nima?", o: ["Moddaning kimyoviy xossalarini saqlab qoluvchi eng kichik zarrasi", "Atom", "Elektron", "Yadro"], c: 0 },
        { q: "Diffuziya nima?", o: ["Moddalarning o'z-o'zidan bir-biriga aralashishi", "Erish", "Qaynash", "Sovush"], c: 0 }
    ],
    "Kimyo": [
        { q: "Suvning kimyoviy formulasi qanday?", o: ["H2O", "CO2", "O2", "H2SO4"], c: 0 },
        { q: "Osh tuzining kimyoviy nomi?", o: ["Natriy xlorid", "Kaliy xlorid", "Kalsiy", "Magniy"], c: 0 },
        { q: "Mendeleyev jadvalida birinchi element?", o: ["Vodorod", "Geliy", "Kislorod", "Azot"], c: 0 },
        { q: "Havoning necha foizi kisloroddan iborat?", o: ["21%", "78%", "1%", "50%"], c: 0 },
        { q: "Organik kimyo nimani o'rganadi?", o: ["Uglerod birikmalarini", "Metallarni", "Suvni", "Toshlarni"], c: 0 },
        { q: "Olmos va grafit nimadan iborat?", o: ["Uglerod", "Temur", "Oltin", "Mis"], c: 0 },
        { q: "Kislota va ishqor reaksiyasi nima deyiladi?", o: ["Neytrallanish", "Oksidlanish", "Bug'lanish", "Erish"], c: 0 },
        { q: "Oltinning kimyoviy belgisi?", o: ["Au", "Ag", "Fe", "Cu"], c: 0 },
        { q: "Kumushning kimyoviy belgisi?", o: ["Ag", "Au", "Pb", "Sn"], c: 0 },
        { q: "Temirning kimyoviy belgisi?", o: ["Fe", "I", "Ir", "F"], c: 0 },
        { q: "Eng yengil gaz?", o: ["Vodorod", "Geliy", "Azot", "Argon"], c: 0 },
        { q: "Fotosintezda nima ajralib chiqadi?", o: ["Kislorod", "Karbonat angidrid", "Vodorod", "Azot"], c: 0 },
        { q: "Muzlash nuqtasi necha gradus?", o: ["0 C", "100 C", "50 C", "-50 C"], c: 0 },
        { q: "Atom yadrosida nimalar bor?", o: ["Proton va neytron", "Elektron", "Faqat proton", "Faqat neytron"], c: 0 },
        { q: "Suyuq metall qaysi?", o: ["Simob", "Oltin", "Mis", "Qalay"], c: 0 },
        { q: "Gazli suvlarda qaysi gaz bo'ladi?", o: ["Karbonat angidrid", "Kislorod", "Azot", "Metan"], c: 0 },
        { q: "Kaliyning belgisi?", o: ["K", "Ka", "Cl", "P"], c: 0 },
        { q: "Kalsiyning belgisi?", o: ["Ca", "C", "Cl", "K"], c: 0 },
        { q: "Sulfat kislota formulasi?", o: ["H2SO4", "HCl", "HNO3", "H2O"], c: 0 },
        { q: "Metanning formulasi?", o: ["CH4", "C2H6", "C3H8", "CO2"], c: 0 },
        { q: "Osh tuzi formulasi?", o: ["NaCl", "KCl", "NaOH", "HCl"], c: 0 },
        { q: "Glinaning asosiy tarkibi?", o: ["Alyuminiy silikat", "Temur", "Kalsiy", "Oltin"], c: 0 },
        { q: "Yodning rangi qanday?", o: ["To'q binafsha (bug'i)", "Yashil", "Qizil", "Oq"], c: 0 },
        { q: "Misning rangi?", o: ["Qizg'ish-jigarrang", "Sariq", "Oq", "Qora"], c: 0 },
        { q: "Eng qattiq tabiiy modda?", o: ["Olmos", "Po'lat", "Granit", "Kvars"], c: 0 },
        { q: "Oksidlanish nima?", o: ["Elektron yo'qotish", "Elektron olish", "Suv qo'shish", "Qizdirish"], c: 0 },
        { q: "Indikator nima?", o: ["Muhitni aniqlovchi modda (lakmus)", "Termometr", "Tarozi", "Lampochka"], c: 0 },
        { q: "Glikozaning formulasi?", o: ["C6H12O6", "C2H5OH", "CH4", "CO2"], c: 0 },
        { q: "Spirtning formulasi (etanol)?", o: ["C2H5OH", "CH3OH", "H2O", "C6H12O6"], c: 0 },
        { q: "Neft nima?", o: ["Uglevodorodlar aralashmasi", "Suv", "Metall", "Tuz"], c: 0 }
    ],
    "Astronomiya": [
        { q: "Quyosh sistemasida nechta sayyora bor?", o: ["8 ta", "9 ta", "7 ta", "10 ta"], c: 0 },
        { q: "Eng katta sayyora qaysi?", o: ["Yupiter", "Saturn", "Mars", "Venera"], c: 0 },
        { q: "Yerga eng yaqin yulduz?", o: ["Quyosh", "Sirius", "Shimol yulduzi", "Betelgeyze"], c: 0 },
        { q: "Qaysi sayyora 'Qizil sayyora' deb ataladi?", o: ["Mars", "Venera", "Yupiter", "Merkuriy"], c: 0 },
        { q: "Saturn sayyorasining asosan nima bilan tanilgan?", o: ["Xalqalari bilan", "Rangi bilan", "Kattaligi bilan", "Yo'ldoshsizligi bilan"], c: 0 },
        { q: "Yulduzlar nima hisobiga porlaydi?", o: ["Termoyadro reaksiyasi", "Elektr", "Aks etish", "Yonish"], c: 0 },
        { q: "Oyda atmosfera bormi?", o: ["Yo'q", "Ha", "Faqat kislorod", "Juda qalin"], c: 0 },
        { q: "Birinchi kosmonavt kim?", o: ["Yuriy Gagarin", "Nil Armstrong", "Valentina Tereshkova", "Leonov"], c: 0 },
        { q: "Oyga birinchi bo'lib kim qadam qo'ygan?", o: ["Nil Armstrong", "Yuriy Gagarin", "Oldrin", "Leonov"], c: 0 },
        { q: "Galaktikamiz nomi nima?", o: ["Somon yo'li", "Andromeda", "Magellan", "Kiyik yo'li"], c: 0 },
        { q: "Yerning o'z o'qi atrofida aylanishi qancha davom etadi?", o: ["24 soat", "365 kun", "12 soat", "30 kun"], c: 0 },
        { q: "Yerning Quyosh atrofida aylanishi qancha?", o: ["365 kun", "24 soat", "1 oy", "100 kun"], c: 0 },
        { q: "Eng kichik sayyora (hozirgi tasnifda)?", o: ["Merkuriy", "Pluton", "Mars", "Venera"], c: 0 },
        { q: "Kometaning 'dumi' nimadan iborat?", o: ["Gaz va chang", "Olov", "Suv", "Metall"], c: 0 },
        { q: "Quyosh tutilishi nima?", o: ["Oy Quyosh va Yer orasiga tushishi", "Yer Quyoshni yopishi", "Bulut to'sishi", "Tungi vaqt"], c: 0 },
        { q: "Oy tutilishi nima?", o: ["Yer Quyosh va Oy orasiga tushishi", "Quyosh yo'qolishi", "Oyning chiqishi", "Yulduz uchishi"], c: 0 },
        { q: "Teleskopni kim birinchi bo'lib astronomiyada ishlatgan?", o: ["Galileo Galiley", "Nyuton", "Kopernik", "Bruno"], c: 0 },
        { q: "Yer markazli (geotsentrik) dunyo sistemasini kim tuzgan?", o: ["Ptolomey", "Kopernik", "Aristotel", "Eynshteyn"], c: 0 },
        { q: "Quyosh markazli (geliotsentrik) sistemani kim yaratgan?", o: ["Nikolay Kopernik", "Ptolomey", "Galiley", "Kepler"], c: 0 },
        { q: "Quyosh sistemasidagi eng issiq sayyora?", o: ["Venera", "Merkuriy", "Mars", "Yupiter"], c: 0 },
        { q: "Venera nega Merkuriyga qaraganda issiqroq?", o: ["Issiqxona effekti (qalin atmosfera) tufayli", "Yaqinligi uchun", "Kattaligi uchun", "Yulduz bo'lgani uchun"], c: 0 },
        { q: "Shoh yulduz deb qaysi yulduz aytiladi?", o: ["Regul", "Sirius", "Shimol yulduzi", "Vega"], c: 2 },
        { q: "Quyosh nurining Yerga yetib kelish vaqti?", o: ["8 daqiqa", "1 daqiqa", "1 soat", "1 soniya"], c: 0 },
        { q: "Kosmosda tovush tarqaladimi?", o: ["Yo'q (vakuum bo'lgani uchun)", "Ha", "Faqat baland tovushlar", "Radioto'lqin orqali"], c: 0 },
        { q: "Qora tuynuk nima?", o: ["O'ta kuchli gravitatsiyali soha", "Kosmik kema", "Yulduz portlashi", "Hech narsa"], c: 0 },
        { q: "Eng yorug' sayyora (Yerdan qaraganda)?", o: ["Venera", "Mars", "Yupiter", "Saturn"], c: 0 },
        { q: "Marsning nechta yo'ldoshi bor?", o: ["2 ta (Fobos va Deymos)", "1 ta", "0 ta", "10 ta"], c: 0 },
        { q: "Yupiterning eng katta yo'ldoshi?", o: ["Ganimed", "Titan", "Oy", "Yevropa"], c: 0 },
        { q: "Yulduz turkumlari nechta?", o: ["88 ta", "12 ta", "100 ta", "50 ta"], c: 0 },
        { q: "Andromeda nima?", o: ["Bizga eng yaqin galaktika", "Sayyora", "Yulduz", "Kometa"], c: 0 }
    ]
};
